from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import torch

from fim.utils.seed import set_seed
from fim_experiments.main import reshape_if_needed, select_benchmark
from fim_experiments.provenance import sha256_file, sha256_json, tensor_sha256


DATASET_SCHEMA_VERSION = 1
SYNTHETIC_LICENSE = "Generated by repository code; project license is currently unspecified."


def _split_indices(size: int, train_fraction: float, seed: int) -> dict[str, list[int]]:
    if size < 3:
        raise ValueError("size must be at least 3")
    if not 0.0 < train_fraction < 1.0:
        raise ValueError("train_fraction must be in (0, 1)")
    generator = torch.Generator(device="cpu").manual_seed(int(seed))
    order = torch.randperm(size, generator=generator).tolist()
    train_count = min(size - 1, max(1, int(size * train_fraction)))
    return {"train": order[:train_count], "validation": order[train_count:]}


def prepare_dataset(
    *,
    benchmark_name: str,
    benchmark_config: dict[str, Any],
    output_dir: str | Path,
    size: int,
    steps: int,
    seed: int,
    train_fraction: float = 0.85,
) -> dict[str, Any]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    set_seed(seed, deterministic=True)
    config = {"name": benchmark_name, "config": benchmark_config}
    benchmark = select_benchmark(config)
    x, y = benchmark.generate_batch(batch_size=int(size), steps=int(steps), device="cpu")
    x, y = reshape_if_needed(x, y)
    if not torch.isfinite(x).all() or not torch.isfinite(y).all():
        raise ValueError("Generated dataset contains non-finite values")

    splits = _split_indices(int(size), train_fraction, int(seed) + 1)
    data_path = output / "dataset.pt"
    torch.save({"x": x.cpu(), "y": y.cpu(), "splits": splits}, data_path)
    manifest = {
        "schema_version": DATASET_SCHEMA_VERSION,
        "created_utc": datetime.now(timezone.utc).isoformat(),
        "name": benchmark_name,
        "source": "deterministic repository generator",
        "license": SYNTHETIC_LICENSE,
        "retrieval_method": "python -m fim.data prepare",
        "generator_config": config,
        "generator_config_sha256": sha256_json(config),
        "seed": int(seed),
        "steps": int(steps),
        "sample_count": int(size),
        "schema": {"x": list(x.shape), "y": list(y.shape), "dtype": str(x.dtype)},
        "splits": {name: len(indices) for name, indices in splits.items()},
        "split_indices_sha256": hashlib.sha256(json.dumps(splits, sort_keys=True).encode()).hexdigest(),
        "tensor_sha256": tensor_sha256((x, y)),
        "artifact_sha256": sha256_file(data_path),
        "known_issues": [
            "Synthetic data are not evidence of natural-domain transfer.",
            "Project-level licensing is unspecified; generated artifacts should not be redistributed as licensed data until resolved.",
        ],
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return manifest


def validate_dataset(output_dir: str | Path) -> dict[str, Any]:
    output = Path(output_dir)
    manifest_path = output / "manifest.json"
    data_path = output / "dataset.pt"
    if not manifest_path.exists() or not data_path.exists():
        raise FileNotFoundError("Expected manifest.json and dataset.pt")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    try:
        payload = torch.load(data_path, map_location="cpu", weights_only=True)
    except TypeError:  # PyTorch < 2.0 compatibility
        payload = torch.load(data_path, map_location="cpu")
    x, y, splits = payload["x"], payload["y"], payload["splits"]
    errors: list[str] = []
    if manifest.get("schema_version") != DATASET_SCHEMA_VERSION:
        errors.append("unsupported schema_version")
    if x.shape[0] != y.shape[0] or x.shape[0] != manifest.get("sample_count"):
        errors.append("sample count mismatch")
    if not torch.isfinite(x).all() or not torch.isfinite(y).all():
        errors.append("non-finite values")
    all_indices = [int(i) for values in splits.values() for i in values]
    if len(all_indices) != len(set(all_indices)):
        errors.append("split overlap")
    if sorted(all_indices) != list(range(x.shape[0])):
        errors.append("splits do not cover dataset exactly")
    if tensor_sha256((x, y)) != manifest.get("tensor_sha256"):
        errors.append("tensor checksum mismatch")
    if sha256_file(data_path) != manifest.get("artifact_sha256"):
        errors.append("artifact checksum mismatch")
    if errors:
        raise ValueError("Dataset validation failed: " + "; ".join(errors))
    return {"valid": True, "sample_count": int(x.shape[0]), "tensor_sha256": manifest["tensor_sha256"]}
